const API_BASE_URL_DEVELOPMENT = "https://localhost:7075";
const API_BASE_URL_PRODUCTION = "https://bugitserver.azurewebsites.net";

const ENDPOINTS = {
  GET_USERS_IN_PROJECT_BY_ID: "get-users-in-project-by-id",
  GET_BUGS_IN_PROJECT_BY_ID: "get-bugs-in-project-by-id",
  GET_PROJECT_IN_ORGANIZATION_BY_ID: "get-project-in-organization-by-id",
  GET_BUG_COMMENT_BY_ID: "get-bug-comment-by-id",
};

const development = {
  API_URL_GET_USERS_IN_PROJECT_BY_ID:
    "${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USERS_IN_PROJECT_BY_ID}",
  API_URL_GET_BUGS_IN_PROJECT_BY_ID:
    "${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_BUGS_IN_PROJECT_BY_ID}",
  API_URL_GET_PROJECT_IN_ORGANIZATION_BY_ID:
    "${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PROJECT_IN_ORGANIZATION_BY_ID}",
  API_URL_GET_BUG_COMMENT_BY_ID:
    "${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_BUG_COMMENT_BY_ID}",
};

const production = {
  API_URL_GET_USERS_IN_PROJECT_BY_ID:
    "${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USERS_IN_PROJECT_BY_ID}",
  API_URL_GET_BUGS_IN_PROJECT_BY_ID:
    "${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_BUGS_IN_PROJECT_BY_ID}",
  API_URL_GET_PROJECT_IN_ORGANIZATION_BY_ID:
    "${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PROJECT_IN_ORGANIZATION_BY_ID}",
  API_URL_GET_BUG_COMMENT_BY_ID:
    "${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_BUG_COMMENT_BY_ID}",
};
